version: "3"
services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./pages:/app/pages